[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.cursor]
cursor = "0xff2600"
text = "0xf1c1c1"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "SF Mono"
style = "Bold"

[font.bold_italic]
family = "SF Mono"
style = "Bold Italic"

[font.italic]
family = "SF Mono"
style = "Regular Italic"

[font.normal]
family = "SF Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "Delete"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u000Ei"
key = "I"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000\t"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000v"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000s"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0000x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000o"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000;"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0000p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0000z"
key = "Return"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00001"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00002"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00003"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00004"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00005"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00006"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00007"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00008"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00009"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000J"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000K"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000L"
key = "Right"
mods = "Command"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Maximized"
