- name: Install packages
  homebrew:
    name:
    - stow
    - tmux
    - powerlevel10k
    - fzf
    - fd
    - ripgrep
    - neovim
    - neovim-remote
    - tldr
    - tree
    state: present

- name: Install cask
  when: ansible_distribution == 'MacOSX'
  homebrew_cask:
    name:
    - alacritty
    - karabiner-elements
    - stats
    - hiddenbar
    - raycast
    - homebrew/cask-fonts/font-sf-mono
    state: present
