- name: Checkout vim plugins
  git:
    repo: https://github.com/{{ item }}
    dest: ~/.local/share/nvim/site/pack/plugins/start/{{ item | basename }}
    force: true
  loop:
  - mhinz/vim-sayonara
  - mbbill/undotree
  - tpope/vim-eunuch
  - kyazdani42/nvim-tree.lua
  - tpope/vim-dispatch
  - AndrewRadev/linediff.vim
  - tpope/vim-repeat
  - tpope/vim-surround
  - tpope/vim-commentary
  - tpope/vim-unimpaired
  - nelstrom/vim-visual-star-search
  - inkarkat/vim-ReplaceWithRegister
  - windwp/nvim-autopairs
  - tommcdo/vim-exchange
  - sainnhe/gruvbox-material
  - ibhagwan/fzf-lua
  - airblade/vim-rooter
  - tpope/vim-fugitive
  - tpope/vim-rhubarb
  - junegunn/gv.vim
  - ellisonleao/glow.nvim
  - neovim/nvim-lsp
  - mfussenegger/nvim-jdtls
  - mfussenegger/nvim-dap
  - mfussenegger/nvim-dap-python
  - leoluz/nvim-dap-go
  - nvim-treesitter/nvim-treesitter
  - nvim-treesitter/nvim-treesitter-textobjects
  - hrsh7th/nvim-cmp
  - hrsh7th/cmp-nvim-lsp
  - hrsh7th/cmp-nvim-lua
  - hrsh7th/cmp-buffer
  - hrsh7th/cmp-path
  - saadparwaiz1/cmp_luasnip
  - L3MON4D3/LuaSnip

# https://github.com/radenling/vim-dispatch-neovim/pull/15
- name: Checkout vim-dispatch-neovim and use pull request
  git:
    repo: https://github.com/radenling/vim-dispatch-neovim
    dest: ~/.local/share/nvim/site/pack/plugins/start/vim-dispatch-neovim
    refspec: pull/15/head:make-terminal-auto-scroll
    version: make-terminal-auto-scroll
    update: no

- name: Checkout amazon vim plugins
  when: ansible_distribution == "amazon"
  git:
    repo: ssh://git.amazon.com:2222/pkg/{{ item }}
    dest: ~/.local/share/nvim/site/pack/plugins/start/{{ item | basename }}
    update: no
  loop:
  - Vim-code-browse
  - VimIon.git

# - name: Checkout opt vim plugins
#   git:
#     repo: https://github.com/{{ item }}
#     dest: ~/.local/share/nvim/site/pack/plugins/opt/{{ item | basename }}
#   loop:
#   - nvim-treesitter/nvim-treesitter
#   - nvim-treesitter/nvim-treesitter-textobjects

# - name: Install nvim-treesitter parsers
#   command: /usr/local/bin/nvim --headless +'TSInstallSync all' +qa

# - name: Update Remote Plugins
#   command: nvim +UpdateRemotePlugins +qa
